[Boilerplate] Fixes order of libraries in LD_ADD
The order of the libraries does matter! At least when using static libraries
the boilerplate examples would not link on my system when using ALUGrid due to missing symbols:

poisson_adaptive-poisson_adaptive.o: In function `Dune::ALU2dGridFactory<Dune::ALUSimplexGrid<2, 2> >::createGrid()':
/home/mblatt/src/dune/2.2/dune-grid/dune/grid/alugrid/2d/alu2dgridfactory.hh:454: undefined reference to `Dune::ALU2dGridFactory<Dune::ALUSimplexGrid<2, 2> >::createGrid(bool, bool, std::string)'
poisson_adaptive-poisson_adaptive.o:(.rodata._ZTVN4Dune11GridFactoryINS_14ALUSimplexGridILi2ELi2EEEEE[_ZTVN4Dune11GridFactoryINS_14ALUSimplexGridILi2ELi2EEEEE]+0x20): undefined reference to `Dune::ALU2dGridFactory<Dune::ALUSimplexGrid<2, 2> >::insertVertex(Dune::FieldVector<double, 2> const&)'
poisson_adaptive-poisson_adaptive.o:(.rodata._ZTVN4Dune11GridFactoryINS_14ALUSimplexGridILi2ELi2EEEEE[_ZTVN4Dune11GridFactoryINS_14ALUSimplexGridILi2ELi2EEEEE]+0x28): undefined reference to `Dune::ALU2dGridFactory<Dune::ALUSimplexGrid<2, 2> >::insertElement(Dune::GeometryType const&, std::vector<unsigned int, std::allocator<unsigned int> > const&)'
...

The problem is that libtool pulls in dependencies from the la files
and makes sure that each library is only
passed to the linker once. Unfortunately, the linker looks for missing
symbols only in subsequent libraries. Therefore passing ALUGRID_LIBS
(or others) before DUNE_LIBS, is an error as libdunegrid.la (that gets
added by DUNE_LIBS) contains a dependency on libalugrid. Therefore in
the previous state libalugrid appeared twice and libtool falsely
stripped the second occurence.

This patch make sure that the libraries appear according to their
dependency. I.e. first DUNE_LIBS then ALUGRID_LIBS and afterwards
MPI_LIBS. Doing it this way libtool will only strip unnecessary libs
and if it doesn't or does not pull in the dependencies, all libraries
are there in the correct order.